---
- name: Remove Ansible via OS packager.
  package:
    name: ansible
    state: absent

- name: Install Ansible via Pip.
  pip:
    name: ansible
    version: "{{ ansible_install_version_pip | default(omit) }}"
